### ISSUE TITLE
Provide URL to room name for easy access 

### ISSUE THREAD

**Issue by arthurzenika** [gpailler/tPresent#9]
It would be nice if one could have an unique URL for the room name, so that we can invite people to that room and they just have to add their Display Name.

**Comment by gpailler** [comment]
It's a great idea!
I will update tPresent as soon I have some availability

Thanks for the request

**Comment by gpailler** [comment]
Deployed 1.0.3 on https://tpresent.pythonanywhere.com/. 
Now, you can use URL fragments to customize display_name, room_name and autostart.

For example the following URL will preconfigure everything and start the app: https://tpresent.pythonanywhere.com/#room_name=Test&display_name=Truc&autostart.

I also added an information panel with the details.
